apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gggx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0004-tenant/tkrw-pr712-0075-0004-app/devfile-sample-gggx@sha256:d0b55984096e0a73bae73fe0c6600d911fa6202d8204f1530dbdd2b0f9383b19
        name: my-nodejs
        resources: {}
status: {}
